spring:
  datasource:
    password: cipher@wVWI5YjcdWzRXkSkVSwgUA==
server:
  servlet:
    context-path: /zhzlgl



# 异步线程配置
async:
  executor:
    thread:
      # 配置核心线程数
      core_pool_size: 10
      # 配置最大线程数
      max_pool_size: 10
      # 配置队列大小
      queue_capacity: 1000
      # 配置线程池中的线程的名称前缀
      name:
        prefix: async-service-

aspectlog:
  enable: true